development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "dev_secret_key_base_#{SecureRandom.hex(64)}" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test_secret_key_base_#{SecureRandom.hex(64)}" %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
